# COURSE: A deep understanding of deep learning
## SECTION: Introduction to Python: functions
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202212

# .
# .
# .

# VIDEO: Inputs and outputs

In [1]:
sum([10,20,30])

60

In [2]:
alist = [2,3,4]

sum(alist)

9

In [3]:
# alist(0)
sum(alist)

9

In [4]:
len(alist)

3

In [5]:
# give outputs
listsum = sum(alist)
print('The sum is ' + str(listsum))

The sum is 9


### Exercise

In [6]:
# compute the average
sum(alist) / len(alist)


3.0

# .
# .
# .

# VIDEO: Python modules (numpy, pandas)


In [7]:
import numpy as np

numbers = [1,2,3,4,5]
np.mean(numbers)
np.average(numbers)

np.float64(3.0)

In [8]:
import numpy as np

np.mean(numbers)

np.float64(3.0)

In [9]:
import numpy as np

np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [10]:
# clear the workspace

In [11]:
# new type: numpy array
numbernp = np.array([1,2,3,4,5])

print(numbernp)
print(numbers)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [12]:
print(type(numbernp))
print(type(numbers))

<class 'numpy.ndarray'>
<class 'list'>


In [13]:
numbernp.min()


np.int64(1)

In [14]:
n = [4,3,5,2,6,1,7]
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]


In [15]:
n = [4,3,5,2,6,1,7]
print(n)
np.sort(n)
print(n)
n = np.sort(n) # notice different variable type; could set back
print(n)

[4, 3, 5, 2, 6, 1, 7]
[4, 3, 5, 2, 6, 1, 7]
[1 2 3 4 5 6 7]


In [16]:
import pandas as pd

# create some random data
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100)>0

# variable labels
labels = ['Temp. (C)','Ice cream']

# create as a dictionary
D = {labels[0]:var1, labels[1]:var2}

# import to pandas dataframe
df = pd.DataFrame(data=D)


In [17]:
df.head()

,Temp. (C),Ice cream
0,13.720113,False
1,16.244151,True
2,25.018304,True
3,23.299221,False
4,25.295234,True


In [18]:
df.count()

,0
Temp. (C),100
Ice cream,100


In [19]:
df.mean()

,0
Temp. (C),19.578495
Ice cream,0.460000


### Exercise

In [20]:
# create a pandas dataframe with variables:
# integers from 0 to 10, their square, and their log

import numpy as np

nums = np.array(range(11))

D = {'v1':nums , 'v2':nums**2 , 'v3':np.log(nums)}

df = pd.DataFrame(D)
df

/tmp/ipykernel_9511/1199125325.py:8: RuntimeWarning: divide by zero encountered in log
  D = {'v1':nums , 'v2':nums**2 , 'v3':np.log(nums)}


,v1,v2,v3
0,0,0,-inf
1,1,1,0.000000
2,2,4,0.693147
3,3,9,1.098612
4,4,16,1.386294
5,5,25,1.609438
6,6,36,1.791759
7,7,49,1.945910
8,8,64,2.079442
9,9,81,2.197225


# VIDEO: Getting help on functions

In [21]:
alist = [1,2,3]

sum(alist,10)

16

In [26]:
sum??

In [23]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [24]:
# advanced method

import inspect
import numpy as np
inspect.getsourcelines(np.linspace)

(['@array_function_dispatch(_linspace_dispatcher)\n',
  'def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,\n',
  '             axis=0, *, device=None):\n',
  '    """\n',
  '    Return evenly spaced numbers over a specified interval.\n',
  '\n',
  '    Returns `num` evenly spaced samples, calculated over the\n',
  '    interval [`start`, `stop`].\n',
  '\n',
  '    The endpoint of the interval can optionally be excluded.\n',
  '\n',
  '    .. versionchanged:: 1.16.0\n',
  '        Non-scalar `start` and `stop` are now supported.\n',
  '\n',
  '    .. versionchanged:: 1.20.0\n',
  '        Values are rounded towards ``-inf`` instead of ``0`` when an\n',
  '        integer ``dtype`` is specified. The old behavior can\n',
  '        still be obtained with ``np.linspace(start, stop, num).astype(int)``\n',
  '\n',
  '    Parameters\n',
  '    ----------\n',
  '    start : array_like\n',
  '        The starting value of the sequence.\n',
  '    stop : array_like\n',

In [25]:
sum('test')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

# .
# .
# .

# VIDEO: Creating functions

In [27]:
def awesomeFunction():
  print(1+1)

In [28]:
awesomeFunction
awesomeFunction()

2


In [29]:
def SuperAwesomeFunction(input1,input2):
  return input1 + input2

In [ ]:
SuperAwesomeFunction(5,8)

In [30]:
answer = SuperAwesomeFunction(5,8)


In [31]:
print(answer)

13


In [32]:
# with multiple outputs
def awesomeFunction(in1,in2):
  sumres = in1+in2
  prodres = in1*in2
  print('Their sum is ' + str(sumres))
  print('Their product is ' + str(prodres))
  return sumres,prodres

In [33]:
out1,out2 = awesomeFunction(4,5)

print(out1,out2)

Their sum is 9
Their product is 20
9 20


In [34]:
# lambda functions

littlefun = lambda x : x**2 - 1

littlefun(4)

15

### Exercise

In [35]:
# create a function that computes a factorial,
# then compare against the numpy factorial function
# hint: import math

def myfactorial(val):
  return np.prod(np.arange(1,val+1))


In [36]:
import math

x = 20 # inaccurate for >~21
print(np.arange(1,x+1))

print(myfactorial(x),math.factorial(x))
math.factorial??


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2432902008176640000 2432902008176640000


# .
# .
# .

# VIDEO: Global and local variable scopes




In [ ]:
# clear the workspace

In [37]:
def funfun():
  x = 7
  y = 10
  print(x)


In [38]:
funfun()

7


In [39]:
x

20

In [40]:
x = 3
print( funfun() )
print( x )
print( y )

7
None
3


NameError: name 'y' is not defined

In [41]:
def funfun():
  print(z)


In [42]:
funfun()

NameError: name 'z' is not defined

In [43]:
z = 3
funfun()

3


In [44]:
# rules:
#  1) variables created inside a function are local (accessible only inside the function)
#  2) variables created outside a function are global (accessible in or out of the function)

### Exercise

In [45]:
# write a function that flips a coin N times and reports the average

import numpy as np

def coinflip(N):
  propCoinFlips = np.mean( np.random.randn(N)>0 )
  print( str(N) + ' coin flips had ' + str(propCoinFlips*100) + '% heads.' )

In [46]:
coinflip(2000)

2000 coin flips had 51.2% heads.


# .
# .
# .

In [47]:
# tangent on copy

a = [4,3]
b = a#[:]
b[0] = 5

print(a)
print(b)

[5, 3]
[5, 3]


In [48]:
print(id(a))
print(id(b))

140662912685440
140662912685440


In [49]:
import copy

a = {'q':1, 'w':2}
b = copy.deepcopy(a)

print(id(a))
print(id(b))

140662912739904
140663475568576


# VIDEO: Classes and object-oriented programming

In [50]:
# class is like a blueprint for a set of attributes and methods
# instance is an example
# class is a cookie cutter, instance is an individual cookie

class model(object):

  # constructor method
  def __init__(self,numlayers,numunits,name):
    self.layers  = numlayers
    self.units   = numunits # these are attributes
    self.name    = name
    self.weights = 10

  # other methods
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} units in the model.')

  def trainTheModel(self,x):
    self.weights += x
    return self.weights

  def __str__(self):
    return f'This is a {self.name} architecture.'


In [51]:
# create an instance and check it
ex = model(2,3,'cnn')
# ex.howManyUnits()
str(ex)

'This is a cnn architecture.'

In [52]:
ex.trainTheModel(3)

13

In [53]:
# Exercise:
# create a new class so that
# 1) the weights is a layers-by-units matrix,
# 2) the weights are changed by multiplying by input x and summing input y

In [54]:
import numpy as np
class model2(object):

  # constructor method
  def __init__(self,numlayers,numunits,name):
    self.layers  = numlayers
    self.units   = numunits # these are attributes
    self.name    = name
    self.weights = np.random.randn(numlayers,self.units)

  # other methods
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} units in the model.')

  def trainTheModel(self,x,y):
    self.weights = self.weights*x + y

  def __str__(self):
    return f'This is a {self.name} architecture.'


In [ ]:
ex1 = model2(2,3,'cnn')
print(ex1.weights)

In [ ]:
ex1.trainTheModel(2,3)

In [ ]:
ex1.weights